version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: facile-nginx
    restart: unless-stopped
    ports:
      - 81:80
      - 444:443
    volumes:
      - ./public:/var/www/html/public
      - ./:/var/www/html/
    depends_on:
      - mysql
      - php
  mysql:
    image: mysql:8.0
    container_name: facile-mysql
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: facile-php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
  npm:
    image: node:18-alpine
    volumes:
      - ./:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
      - php
    entrypoint: ["php", "/var/www/html/artisan"]
