version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: facile-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public:/var/www/html/public
    depends_on:
      - mysql
      - php

  mysql:
    image: mysql:8.0
    container_name: facile-mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: facile-php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
